name: Autograding

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar pytest
        run: pip install pytest

      - name: Ejecutar tests
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pytest Semana5/tests

